name: default
mappings:
  - name: Forward Punch
    control: space
    motion: punch_forward
  - name: Uppercut
    control: e
    motion: uppercut
  - name: Hadoken
    control: "1"
    motion: hadoken
